apiVersion: apps/v1
kind: Deployment
metadata:
  name: nba
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nba
  template:
    metadata:
      labels:
        app: nba
    spec:
      containers:
      - image: okteto.dev/nba:latest
        name: nba
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "d1a37602-041c-4412-b6bd-10369fecc62a"
        - name: Vless_Path
          value: "/gfyuiugyfts"
        - name: Vmess_UUID
          value: "d1a37602-041c-4412-b6bd-10369fecc62a"
        - name: Vmess_Path
          value: "/dsesrytyvtdrsewdtr"
        - name: Share_Path
          value: "/v2link"
